#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaXe_QuocVuong.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NHAXE_QUOCVUONG")]
	public partial class NhaXeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    partial void InsertChiTietVe(ChiTietVe instance);
    partial void UpdateChiTietVe(ChiTietVe instance);
    partial void DeleteChiTietVe(ChiTietVe instance);
    partial void InsertDiaDiem(DiaDiem instance);
    partial void UpdateDiaDiem(DiaDiem instance);
    partial void DeleteDiaDiem(DiaDiem instance);
    partial void InsertDoanhThu(DoanhThu instance);
    partial void UpdateDoanhThu(DoanhThu instance);
    partial void DeleteDoanhThu(DoanhThu instance);
    partial void InsertGhe(Ghe instance);
    partial void UpdateGhe(Ghe instance);
    partial void DeleteGhe(Ghe instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLichTrinh(LichTrinh instance);
    partial void UpdateLichTrinh(LichTrinh instance);
    partial void DeleteLichTrinh(LichTrinh instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHUONG_THUC_THANH_TOAN(PHUONG_THUC_THANH_TOAN instance);
    partial void UpdatePHUONG_THUC_THANH_TOAN(PHUONG_THUC_THANH_TOAN instance);
    partial void DeletePHUONG_THUC_THANH_TOAN(PHUONG_THUC_THANH_TOAN instance);
    partial void InsertTuyenDuong(TuyenDuong instance);
    partial void UpdateTuyenDuong(TuyenDuong instance);
    partial void DeleteTuyenDuong(TuyenDuong instance);
    partial void InsertThemTramDungChan(ThemTramDungChan instance);
    partial void UpdateThemTramDungChan(ThemTramDungChan instance);
    partial void DeleteThemTramDungChan(ThemTramDungChan instance);
    partial void InsertTramDungChan(TramDungChan instance);
    partial void UpdateTramDungChan(TramDungChan instance);
    partial void DeleteTramDungChan(TramDungChan instance);
    partial void InsertuserAccount(userAccount instance);
    partial void UpdateuserAccount(userAccount instance);
    partial void DeleteuserAccount(userAccount instance);
    partial void InsertVe(Ve instance);
    partial void UpdateVe(Ve instance);
    partial void DeleteVe(Ve instance);
    #endregion
		
		public NhaXeDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NHAXE_QUOCVUONGConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NhaXeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NhaXeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NhaXeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NhaXeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietVe> ChiTietVes
		{
			get
			{
				return this.GetTable<ChiTietVe>();
			}
		}
		
		public System.Data.Linq.Table<DiaDiem> DiaDiems
		{
			get
			{
				return this.GetTable<DiaDiem>();
			}
		}
		
		public System.Data.Linq.Table<DoanhThu> DoanhThus
		{
			get
			{
				return this.GetTable<DoanhThu>();
			}
		}
		
		public System.Data.Linq.Table<Ghe> Ghes
		{
			get
			{
				return this.GetTable<Ghe>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LichTrinh> LichTrinhs
		{
			get
			{
				return this.GetTable<LichTrinh>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHUONG_THUC_THANH_TOAN> PHUONG_THUC_THANH_TOANs
		{
			get
			{
				return this.GetTable<PHUONG_THUC_THANH_TOAN>();
			}
		}
		
		public System.Data.Linq.Table<TuyenDuong> TuyenDuongs
		{
			get
			{
				return this.GetTable<TuyenDuong>();
			}
		}
		
		public System.Data.Linq.Table<ThemTramDungChan> ThemTramDungChans
		{
			get
			{
				return this.GetTable<ThemTramDungChan>();
			}
		}
		
		public System.Data.Linq.Table<TramDungChan> TramDungChans
		{
			get
			{
				return this.GetTable<TramDungChan>();
			}
		}
		
		public System.Data.Linq.Table<userAccount> userAccounts
		{
			get
			{
				return this.GetTable<userAccount>();
			}
		}
		
		public System.Data.Linq.Table<Ve> Ves
		{
			get
			{
				return this.GetTable<Ve>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_XE;
		
		private string _BIEN_SO_XE;
		
		private string _LOAI_XE;
		
		private int _SO_GHE;
		
		private System.DateTime _NGAY_THEM_XE;
		
		private EntitySet<LichTrinh> _LichTrinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_XEChanging(int value);
    partial void OnID_XEChanged();
    partial void OnBIEN_SO_XEChanging(string value);
    partial void OnBIEN_SO_XEChanged();
    partial void OnLOAI_XEChanging(string value);
    partial void OnLOAI_XEChanged();
    partial void OnSO_GHEChanging(int value);
    partial void OnSO_GHEChanged();
    partial void OnNGAY_THEM_XEChanging(System.DateTime value);
    partial void OnNGAY_THEM_XEChanged();
    #endregion
		
		public Xe()
		{
			this._LichTrinhs = new EntitySet<LichTrinh>(new Action<LichTrinh>(this.attach_LichTrinhs), new Action<LichTrinh>(this.detach_LichTrinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_XE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_XE
		{
			get
			{
				return this._ID_XE;
			}
			set
			{
				if ((this._ID_XE != value))
				{
					this.OnID_XEChanging(value);
					this.SendPropertyChanging();
					this._ID_XE = value;
					this.SendPropertyChanged("ID_XE");
					this.OnID_XEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIEN_SO_XE", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string BIEN_SO_XE
		{
			get
			{
				return this._BIEN_SO_XE;
			}
			set
			{
				if ((this._BIEN_SO_XE != value))
				{
					this.OnBIEN_SO_XEChanging(value);
					this.SendPropertyChanging();
					this._BIEN_SO_XE = value;
					this.SendPropertyChanged("BIEN_SO_XE");
					this.OnBIEN_SO_XEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAI_XE", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string LOAI_XE
		{
			get
			{
				return this._LOAI_XE;
			}
			set
			{
				if ((this._LOAI_XE != value))
				{
					this.OnLOAI_XEChanging(value);
					this.SendPropertyChanging();
					this._LOAI_XE = value;
					this.SendPropertyChanged("LOAI_XE");
					this.OnLOAI_XEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_GHE", DbType="Int NOT NULL")]
		public int SO_GHE
		{
			get
			{
				return this._SO_GHE;
			}
			set
			{
				if ((this._SO_GHE != value))
				{
					this.OnSO_GHEChanging(value);
					this.SendPropertyChanging();
					this._SO_GHE = value;
					this.SendPropertyChanged("SO_GHE");
					this.OnSO_GHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_THEM_XE", DbType="DateTime NOT NULL")]
		public System.DateTime NGAY_THEM_XE
		{
			get
			{
				return this._NGAY_THEM_XE;
			}
			set
			{
				if ((this._NGAY_THEM_XE != value))
				{
					this.OnNGAY_THEM_XEChanging(value);
					this.SendPropertyChanging();
					this._NGAY_THEM_XE = value;
					this.SendPropertyChanged("NGAY_THEM_XE");
					this.OnNGAY_THEM_XEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_LichTrinh", Storage="_LichTrinhs", ThisKey="ID_XE", OtherKey="ID_XE")]
		public EntitySet<LichTrinh> LichTrinhs
		{
			get
			{
				return this._LichTrinhs;
			}
			set
			{
				this._LichTrinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichTrinhs(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.Xe = this;
		}
		
		private void detach_LichTrinhs(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.Xe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietVe")]
	public partial class ChiTietVe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_VE;
		
		private string _VI_TRI_NGOI;
		
		private EntityRef<Ghe> _Ghe;
		
		private EntityRef<Ve> _Ve;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VEChanging(string value);
    partial void OnID_VEChanged();
    partial void OnVI_TRI_NGOIChanging(string value);
    partial void OnVI_TRI_NGOIChanged();
    #endregion
		
		public ChiTietVe()
		{
			this._Ghe = default(EntityRef<Ghe>);
			this._Ve = default(EntityRef<Ve>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VE", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_VE
		{
			get
			{
				return this._ID_VE;
			}
			set
			{
				if ((this._ID_VE != value))
				{
					if (this._Ve.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_VEChanging(value);
					this.SendPropertyChanging();
					this._ID_VE = value;
					this.SendPropertyChanged("ID_VE");
					this.OnID_VEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VI_TRI_NGOI", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string VI_TRI_NGOI
		{
			get
			{
				return this._VI_TRI_NGOI;
			}
			set
			{
				if ((this._VI_TRI_NGOI != value))
				{
					if (this._Ghe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVI_TRI_NGOIChanging(value);
					this.SendPropertyChanging();
					this._VI_TRI_NGOI = value;
					this.SendPropertyChanged("VI_TRI_NGOI");
					this.OnVI_TRI_NGOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ghe_ChiTietVe", Storage="_Ghe", ThisKey="VI_TRI_NGOI", OtherKey="ID_GHE", IsForeignKey=true)]
		public Ghe Ghe
		{
			get
			{
				return this._Ghe.Entity;
			}
			set
			{
				Ghe previousValue = this._Ghe.Entity;
				if (((previousValue != value) 
							|| (this._Ghe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ghe.Entity = null;
						previousValue.ChiTietVes.Remove(this);
					}
					this._Ghe.Entity = value;
					if ((value != null))
					{
						value.ChiTietVes.Add(this);
						this._VI_TRI_NGOI = value.ID_GHE;
					}
					else
					{
						this._VI_TRI_NGOI = default(string);
					}
					this.SendPropertyChanged("Ghe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ve_ChiTietVe", Storage="_Ve", ThisKey="ID_VE", OtherKey="ID_VE", IsForeignKey=true)]
		public Ve Ve
		{
			get
			{
				return this._Ve.Entity;
			}
			set
			{
				Ve previousValue = this._Ve.Entity;
				if (((previousValue != value) 
							|| (this._Ve.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ve.Entity = null;
						previousValue.ChiTietVes.Remove(this);
					}
					this._Ve.Entity = value;
					if ((value != null))
					{
						value.ChiTietVes.Add(this);
						this._ID_VE = value.ID_VE;
					}
					else
					{
						this._ID_VE = default(string);
					}
					this.SendPropertyChanged("Ve");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaDiem")]
	public partial class DiaDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DIADIEM;
		
		private string _TEN_TINH_THANH;
		
		private EntitySet<TuyenDuong> _TuyenDuongs;
		
		private EntitySet<TuyenDuong> _TuyenDuongs1;
		
		private EntitySet<TramDungChan> _TramDungChans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DIADIEMChanging(int value);
    partial void OnID_DIADIEMChanged();
    partial void OnTEN_TINH_THANHChanging(string value);
    partial void OnTEN_TINH_THANHChanged();
    #endregion
		
		public DiaDiem()
		{
			this._TuyenDuongs = new EntitySet<TuyenDuong>(new Action<TuyenDuong>(this.attach_TuyenDuongs), new Action<TuyenDuong>(this.detach_TuyenDuongs));
			this._TuyenDuongs1 = new EntitySet<TuyenDuong>(new Action<TuyenDuong>(this.attach_TuyenDuongs1), new Action<TuyenDuong>(this.detach_TuyenDuongs1));
			this._TramDungChans = new EntitySet<TramDungChan>(new Action<TramDungChan>(this.attach_TramDungChans), new Action<TramDungChan>(this.detach_TramDungChans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DIADIEM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DIADIEM
		{
			get
			{
				return this._ID_DIADIEM;
			}
			set
			{
				if ((this._ID_DIADIEM != value))
				{
					this.OnID_DIADIEMChanging(value);
					this.SendPropertyChanging();
					this._ID_DIADIEM = value;
					this.SendPropertyChanged("ID_DIADIEM");
					this.OnID_DIADIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TINH_THANH", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TEN_TINH_THANH
		{
			get
			{
				return this._TEN_TINH_THANH;
			}
			set
			{
				if ((this._TEN_TINH_THANH != value))
				{
					this.OnTEN_TINH_THANHChanging(value);
					this.SendPropertyChanging();
					this._TEN_TINH_THANH = value;
					this.SendPropertyChanged("TEN_TINH_THANH");
					this.OnTEN_TINH_THANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TuyenDuong", Storage="_TuyenDuongs", ThisKey="ID_DIADIEM", OtherKey="DIEM_DAU")]
		public EntitySet<TuyenDuong> TuyenDuongs
		{
			get
			{
				return this._TuyenDuongs;
			}
			set
			{
				this._TuyenDuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TuyenDuong1", Storage="_TuyenDuongs1", ThisKey="ID_DIADIEM", OtherKey="DIEM_CUOI")]
		public EntitySet<TuyenDuong> TuyenDuongs1
		{
			get
			{
				return this._TuyenDuongs1;
			}
			set
			{
				this._TuyenDuongs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TramDungChan", Storage="_TramDungChans", ThisKey="ID_DIADIEM", OtherKey="ID_DIADIEM")]
		public EntitySet<TramDungChan> TramDungChans
		{
			get
			{
				return this._TramDungChans;
			}
			set
			{
				this._TramDungChans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = this;
		}
		
		private void detach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = null;
		}
		
		private void attach_TuyenDuongs1(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem1 = this;
		}
		
		private void detach_TuyenDuongs1(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem1 = null;
		}
		
		private void attach_TramDungChans(TramDungChan entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = this;
		}
		
		private void detach_TramDungChans(TramDungChan entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanhThu")]
	public partial class DoanhThu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_DOANHTHU;
		
		private string _MA_LICH_TRINH;
		
		private System.Nullable<int> _SO_VE_DA_DAT;
		
		private System.Nullable<double> _TONGTIEN;
		
		private EntityRef<LichTrinh> _LichTrinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DOANHTHUChanging(string value);
    partial void OnID_DOANHTHUChanged();
    partial void OnMA_LICH_TRINHChanging(string value);
    partial void OnMA_LICH_TRINHChanged();
    partial void OnSO_VE_DA_DATChanging(System.Nullable<int> value);
    partial void OnSO_VE_DA_DATChanged();
    partial void OnTONGTIENChanging(System.Nullable<double> value);
    partial void OnTONGTIENChanged();
    #endregion
		
		public DoanhThu()
		{
			this._LichTrinh = default(EntityRef<LichTrinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DOANHTHU", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_DOANHTHU
		{
			get
			{
				return this._ID_DOANHTHU;
			}
			set
			{
				if ((this._ID_DOANHTHU != value))
				{
					this.OnID_DOANHTHUChanging(value);
					this.SendPropertyChanging();
					this._ID_DOANHTHU = value;
					this.SendPropertyChanged("ID_DOANHTHU");
					this.OnID_DOANHTHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LICH_TRINH", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string MA_LICH_TRINH
		{
			get
			{
				return this._MA_LICH_TRINH;
			}
			set
			{
				if ((this._MA_LICH_TRINH != value))
				{
					if (this._LichTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._MA_LICH_TRINH = value;
					this.SendPropertyChanged("MA_LICH_TRINH");
					this.OnMA_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_VE_DA_DAT", DbType="Int")]
		public System.Nullable<int> SO_VE_DA_DAT
		{
			get
			{
				return this._SO_VE_DA_DAT;
			}
			set
			{
				if ((this._SO_VE_DA_DAT != value))
				{
					this.OnSO_VE_DA_DATChanging(value);
					this.SendPropertyChanging();
					this._SO_VE_DA_DAT = value;
					this.SendPropertyChanged("SO_VE_DA_DAT");
					this.OnSO_VE_DA_DATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Float")]
		public System.Nullable<double> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_DoanhThu", Storage="_LichTrinh", ThisKey="MA_LICH_TRINH", OtherKey="MA_LICH_TRINH", IsForeignKey=true)]
		public LichTrinh LichTrinh
		{
			get
			{
				return this._LichTrinh.Entity;
			}
			set
			{
				LichTrinh previousValue = this._LichTrinh.Entity;
				if (((previousValue != value) 
							|| (this._LichTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichTrinh.Entity = null;
						previousValue.DoanhThus.Remove(this);
					}
					this._LichTrinh.Entity = value;
					if ((value != null))
					{
						value.DoanhThus.Add(this);
						this._MA_LICH_TRINH = value.MA_LICH_TRINH;
					}
					else
					{
						this._MA_LICH_TRINH = default(string);
					}
					this.SendPropertyChanged("LichTrinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ghe")]
	public partial class Ghe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_GHE;
		
		private string _VI_TRI_NGOI;
		
		private string _MA_LICH_TRINH;
		
		private bool _TINH_TRANG;
		
		private EntitySet<ChiTietVe> _ChiTietVes;
		
		private EntityRef<LichTrinh> _LichTrinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_GHEChanging(string value);
    partial void OnID_GHEChanged();
    partial void OnVI_TRI_NGOIChanging(string value);
    partial void OnVI_TRI_NGOIChanged();
    partial void OnMA_LICH_TRINHChanging(string value);
    partial void OnMA_LICH_TRINHChanged();
    partial void OnTINH_TRANGChanging(bool value);
    partial void OnTINH_TRANGChanged();
    #endregion
		
		public Ghe()
		{
			this._ChiTietVes = new EntitySet<ChiTietVe>(new Action<ChiTietVe>(this.attach_ChiTietVes), new Action<ChiTietVe>(this.detach_ChiTietVes));
			this._LichTrinh = default(EntityRef<LichTrinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_GHE", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_GHE
		{
			get
			{
				return this._ID_GHE;
			}
			set
			{
				if ((this._ID_GHE != value))
				{
					this.OnID_GHEChanging(value);
					this.SendPropertyChanging();
					this._ID_GHE = value;
					this.SendPropertyChanged("ID_GHE");
					this.OnID_GHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VI_TRI_NGOI", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string VI_TRI_NGOI
		{
			get
			{
				return this._VI_TRI_NGOI;
			}
			set
			{
				if ((this._VI_TRI_NGOI != value))
				{
					this.OnVI_TRI_NGOIChanging(value);
					this.SendPropertyChanging();
					this._VI_TRI_NGOI = value;
					this.SendPropertyChanged("VI_TRI_NGOI");
					this.OnVI_TRI_NGOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LICH_TRINH", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string MA_LICH_TRINH
		{
			get
			{
				return this._MA_LICH_TRINH;
			}
			set
			{
				if ((this._MA_LICH_TRINH != value))
				{
					if (this._LichTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._MA_LICH_TRINH = value;
					this.SendPropertyChanged("MA_LICH_TRINH");
					this.OnMA_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINH_TRANG", DbType="Bit NOT NULL")]
		public bool TINH_TRANG
		{
			get
			{
				return this._TINH_TRANG;
			}
			set
			{
				if ((this._TINH_TRANG != value))
				{
					this.OnTINH_TRANGChanging(value);
					this.SendPropertyChanging();
					this._TINH_TRANG = value;
					this.SendPropertyChanged("TINH_TRANG");
					this.OnTINH_TRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ghe_ChiTietVe", Storage="_ChiTietVes", ThisKey="ID_GHE", OtherKey="VI_TRI_NGOI")]
		public EntitySet<ChiTietVe> ChiTietVes
		{
			get
			{
				return this._ChiTietVes;
			}
			set
			{
				this._ChiTietVes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_Ghe", Storage="_LichTrinh", ThisKey="MA_LICH_TRINH", OtherKey="MA_LICH_TRINH", IsForeignKey=true)]
		public LichTrinh LichTrinh
		{
			get
			{
				return this._LichTrinh.Entity;
			}
			set
			{
				LichTrinh previousValue = this._LichTrinh.Entity;
				if (((previousValue != value) 
							|| (this._LichTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichTrinh.Entity = null;
						previousValue.Ghes.Remove(this);
					}
					this._LichTrinh.Entity = value;
					if ((value != null))
					{
						value.Ghes.Add(this);
						this._MA_LICH_TRINH = value.MA_LICH_TRINH;
					}
					else
					{
						this._MA_LICH_TRINH = default(string);
					}
					this.SendPropertyChanged("LichTrinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietVes(ChiTietVe entity)
		{
			this.SendPropertyChanging();
			entity.Ghe = this;
		}
		
		private void detach_ChiTietVes(ChiTietVe entity)
		{
			this.SendPropertyChanging();
			entity.Ghe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERNAME;
		
		private string _TEN_KHACH_HANG;
		
		private string _SO_DIEN_THOAI;
		
		private string _EMAIL;
		
		private EntitySet<Ve> _Ves;
		
		private EntityRef<userAccount> _userAccount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnTEN_KHACH_HANGChanging(string value);
    partial void OnTEN_KHACH_HANGChanged();
    partial void OnSO_DIEN_THOAIChanging(string value);
    partial void OnSO_DIEN_THOAIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public KhachHang()
		{
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			this._userAccount = default(EntityRef<userAccount>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					if (this._userAccount.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_KHACH_HANG", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TEN_KHACH_HANG
		{
			get
			{
				return this._TEN_KHACH_HANG;
			}
			set
			{
				if ((this._TEN_KHACH_HANG != value))
				{
					this.OnTEN_KHACH_HANGChanging(value);
					this.SendPropertyChanging();
					this._TEN_KHACH_HANG = value;
					this.SendPropertyChanged("TEN_KHACH_HANG");
					this.OnTEN_KHACH_HANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_DIEN_THOAI", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string SO_DIEN_THOAI
		{
			get
			{
				return this._SO_DIEN_THOAI;
			}
			set
			{
				if ((this._SO_DIEN_THOAI != value))
				{
					this.OnSO_DIEN_THOAIChanging(value);
					this.SendPropertyChanging();
					this._SO_DIEN_THOAI = value;
					this.SendPropertyChanged("SO_DIEN_THOAI");
					this.OnSO_DIEN_THOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_Ve", Storage="_Ves", ThisKey="USERNAME", OtherKey="ID_KHACH_HANG")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="userAccount_KhachHang", Storage="_userAccount", ThisKey="USERNAME", OtherKey="username", IsForeignKey=true)]
		public userAccount userAccount
		{
			get
			{
				return this._userAccount.Entity;
			}
			set
			{
				userAccount previousValue = this._userAccount.Entity;
				if (((previousValue != value) 
							|| (this._userAccount.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._userAccount.Entity = null;
						previousValue.KhachHang = null;
					}
					this._userAccount.Entity = value;
					if ((value != null))
					{
						value.KhachHang = this;
						this._USERNAME = value.username;
					}
					else
					{
						this._USERNAME = default(string);
					}
					this.SendPropertyChanged("userAccount");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichTrinh")]
	public partial class LichTrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_LICH_TRINH;
		
		private int _ID_TUYEN_DUONG;
		
		private System.DateTime _KHOI_HANH;
		
		private System.DateTime _KET_THUC;
		
		private double _GIA_VE;
		
		private int _ID_XE;
		
		private System.Nullable<double> _CHI_PHI_PHAT_SINH;
		
		private string _TRANG_THAI;
		
		private string _TAIXE;
		
		private System.DateTime _NGAY_TAO_LICH_TRINH;
		
		private string _NGUOI_TAO_LICH_TRINH;
		
		private EntitySet<DoanhThu> _DoanhThus;
		
		private EntitySet<Ghe> _Ghes;
		
		private EntitySet<ThemTramDungChan> _ThemTramDungChans;
		
		private EntitySet<Ve> _Ves;
		
		private EntityRef<Xe> _Xe;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<NHANVIEN> _NHANVIEN1;
		
		private EntityRef<TuyenDuong> _TuyenDuong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_LICH_TRINHChanging(string value);
    partial void OnMA_LICH_TRINHChanged();
    partial void OnID_TUYEN_DUONGChanging(int value);
    partial void OnID_TUYEN_DUONGChanged();
    partial void OnKHOI_HANHChanging(System.DateTime value);
    partial void OnKHOI_HANHChanged();
    partial void OnKET_THUCChanging(System.DateTime value);
    partial void OnKET_THUCChanged();
    partial void OnGIA_VEChanging(double value);
    partial void OnGIA_VEChanged();
    partial void OnID_XEChanging(int value);
    partial void OnID_XEChanged();
    partial void OnCHI_PHI_PHAT_SINHChanging(System.Nullable<double> value);
    partial void OnCHI_PHI_PHAT_SINHChanged();
    partial void OnTRANG_THAIChanging(string value);
    partial void OnTRANG_THAIChanged();
    partial void OnTAIXEChanging(string value);
    partial void OnTAIXEChanged();
    partial void OnNGAY_TAO_LICH_TRINHChanging(System.DateTime value);
    partial void OnNGAY_TAO_LICH_TRINHChanged();
    partial void OnNGUOI_TAO_LICH_TRINHChanging(string value);
    partial void OnNGUOI_TAO_LICH_TRINHChanged();
    #endregion
		
		public LichTrinh()
		{
			this._DoanhThus = new EntitySet<DoanhThu>(new Action<DoanhThu>(this.attach_DoanhThus), new Action<DoanhThu>(this.detach_DoanhThus));
			this._Ghes = new EntitySet<Ghe>(new Action<Ghe>(this.attach_Ghes), new Action<Ghe>(this.detach_Ghes));
			this._ThemTramDungChans = new EntitySet<ThemTramDungChan>(new Action<ThemTramDungChan>(this.attach_ThemTramDungChans), new Action<ThemTramDungChan>(this.detach_ThemTramDungChans));
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			this._Xe = default(EntityRef<Xe>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._NHANVIEN1 = default(EntityRef<NHANVIEN>);
			this._TuyenDuong = default(EntityRef<TuyenDuong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LICH_TRINH", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_LICH_TRINH
		{
			get
			{
				return this._MA_LICH_TRINH;
			}
			set
			{
				if ((this._MA_LICH_TRINH != value))
				{
					this.OnMA_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._MA_LICH_TRINH = value;
					this.SendPropertyChanged("MA_LICH_TRINH");
					this.OnMA_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TUYEN_DUONG", DbType="Int NOT NULL")]
		public int ID_TUYEN_DUONG
		{
			get
			{
				return this._ID_TUYEN_DUONG;
			}
			set
			{
				if ((this._ID_TUYEN_DUONG != value))
				{
					if (this._TuyenDuong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TUYEN_DUONGChanging(value);
					this.SendPropertyChanging();
					this._ID_TUYEN_DUONG = value;
					this.SendPropertyChanged("ID_TUYEN_DUONG");
					this.OnID_TUYEN_DUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHOI_HANH", DbType="DateTime NOT NULL")]
		public System.DateTime KHOI_HANH
		{
			get
			{
				return this._KHOI_HANH;
			}
			set
			{
				if ((this._KHOI_HANH != value))
				{
					this.OnKHOI_HANHChanging(value);
					this.SendPropertyChanging();
					this._KHOI_HANH = value;
					this.SendPropertyChanged("KHOI_HANH");
					this.OnKHOI_HANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KET_THUC", DbType="DateTime NOT NULL")]
		public System.DateTime KET_THUC
		{
			get
			{
				return this._KET_THUC;
			}
			set
			{
				if ((this._KET_THUC != value))
				{
					this.OnKET_THUCChanging(value);
					this.SendPropertyChanging();
					this._KET_THUC = value;
					this.SendPropertyChanged("KET_THUC");
					this.OnKET_THUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_VE", DbType="Float NOT NULL")]
		public double GIA_VE
		{
			get
			{
				return this._GIA_VE;
			}
			set
			{
				if ((this._GIA_VE != value))
				{
					this.OnGIA_VEChanging(value);
					this.SendPropertyChanging();
					this._GIA_VE = value;
					this.SendPropertyChanged("GIA_VE");
					this.OnGIA_VEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_XE", DbType="Int NOT NULL")]
		public int ID_XE
		{
			get
			{
				return this._ID_XE;
			}
			set
			{
				if ((this._ID_XE != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_XEChanging(value);
					this.SendPropertyChanging();
					this._ID_XE = value;
					this.SendPropertyChanged("ID_XE");
					this.OnID_XEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHI_PHI_PHAT_SINH", DbType="Float")]
		public System.Nullable<double> CHI_PHI_PHAT_SINH
		{
			get
			{
				return this._CHI_PHI_PHAT_SINH;
			}
			set
			{
				if ((this._CHI_PHI_PHAT_SINH != value))
				{
					this.OnCHI_PHI_PHAT_SINHChanging(value);
					this.SendPropertyChanging();
					this._CHI_PHI_PHAT_SINH = value;
					this.SendPropertyChanged("CHI_PHI_PHAT_SINH");
					this.OnCHI_PHI_PHAT_SINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANG_THAI", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string TRANG_THAI
		{
			get
			{
				return this._TRANG_THAI;
			}
			set
			{
				if ((this._TRANG_THAI != value))
				{
					this.OnTRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._TRANG_THAI = value;
					this.SendPropertyChanged("TRANG_THAI");
					this.OnTRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIXE", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string TAIXE
		{
			get
			{
				return this._TAIXE;
			}
			set
			{
				if ((this._TAIXE != value))
				{
					if (this._NHANVIEN1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTAIXEChanging(value);
					this.SendPropertyChanging();
					this._TAIXE = value;
					this.SendPropertyChanged("TAIXE");
					this.OnTAIXEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_TAO_LICH_TRINH", DbType="DateTime NOT NULL")]
		public System.DateTime NGAY_TAO_LICH_TRINH
		{
			get
			{
				return this._NGAY_TAO_LICH_TRINH;
			}
			set
			{
				if ((this._NGAY_TAO_LICH_TRINH != value))
				{
					this.OnNGAY_TAO_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._NGAY_TAO_LICH_TRINH = value;
					this.SendPropertyChanged("NGAY_TAO_LICH_TRINH");
					this.OnNGAY_TAO_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOI_TAO_LICH_TRINH", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string NGUOI_TAO_LICH_TRINH
		{
			get
			{
				return this._NGUOI_TAO_LICH_TRINH;
			}
			set
			{
				if ((this._NGUOI_TAO_LICH_TRINH != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNGUOI_TAO_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._NGUOI_TAO_LICH_TRINH = value;
					this.SendPropertyChanged("NGUOI_TAO_LICH_TRINH");
					this.OnNGUOI_TAO_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_DoanhThu", Storage="_DoanhThus", ThisKey="MA_LICH_TRINH", OtherKey="MA_LICH_TRINH")]
		public EntitySet<DoanhThu> DoanhThus
		{
			get
			{
				return this._DoanhThus;
			}
			set
			{
				this._DoanhThus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_Ghe", Storage="_Ghes", ThisKey="MA_LICH_TRINH", OtherKey="MA_LICH_TRINH")]
		public EntitySet<Ghe> Ghes
		{
			get
			{
				return this._Ghes;
			}
			set
			{
				this._Ghes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_ThemTramDungChan", Storage="_ThemTramDungChans", ThisKey="MA_LICH_TRINH", OtherKey="MA_LICH_TRINH")]
		public EntitySet<ThemTramDungChan> ThemTramDungChans
		{
			get
			{
				return this._ThemTramDungChans;
			}
			set
			{
				this._ThemTramDungChans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_Ve", Storage="_Ves", ThisKey="MA_LICH_TRINH", OtherKey="ID_LICH_TRINH")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_LichTrinh", Storage="_Xe", ThisKey="ID_XE", OtherKey="ID_XE", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.LichTrinhs.Remove(this);
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.LichTrinhs.Add(this);
						this._ID_XE = value.ID_XE;
					}
					else
					{
						this._ID_XE = default(int);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_LichTrinh", Storage="_NHANVIEN", ThisKey="NGUOI_TAO_LICH_TRINH", OtherKey="USERNAME", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.LichTrinhs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.LichTrinhs.Add(this);
						this._NGUOI_TAO_LICH_TRINH = value.USERNAME;
					}
					else
					{
						this._NGUOI_TAO_LICH_TRINH = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_LichTrinh1", Storage="_NHANVIEN1", ThisKey="TAIXE", OtherKey="USERNAME", IsForeignKey=true)]
		public NHANVIEN NHANVIEN1
		{
			get
			{
				return this._NHANVIEN1.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN1.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN1.Entity = null;
						previousValue.LichTrinhs1.Remove(this);
					}
					this._NHANVIEN1.Entity = value;
					if ((value != null))
					{
						value.LichTrinhs1.Add(this);
						this._TAIXE = value.USERNAME;
					}
					else
					{
						this._TAIXE = default(string);
					}
					this.SendPropertyChanged("NHANVIEN1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenDuong_LichTrinh", Storage="_TuyenDuong", ThisKey="ID_TUYEN_DUONG", OtherKey="ID_TUYEN", IsForeignKey=true)]
		public TuyenDuong TuyenDuong
		{
			get
			{
				return this._TuyenDuong.Entity;
			}
			set
			{
				TuyenDuong previousValue = this._TuyenDuong.Entity;
				if (((previousValue != value) 
							|| (this._TuyenDuong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuyenDuong.Entity = null;
						previousValue.LichTrinhs.Remove(this);
					}
					this._TuyenDuong.Entity = value;
					if ((value != null))
					{
						value.LichTrinhs.Add(this);
						this._ID_TUYEN_DUONG = value.ID_TUYEN;
					}
					else
					{
						this._ID_TUYEN_DUONG = default(int);
					}
					this.SendPropertyChanged("TuyenDuong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DoanhThus(DoanhThu entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = this;
		}
		
		private void detach_DoanhThus(DoanhThu entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = null;
		}
		
		private void attach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = this;
		}
		
		private void detach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = null;
		}
		
		private void attach_ThemTramDungChans(ThemTramDungChan entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = this;
		}
		
		private void detach_ThemTramDungChans(ThemTramDungChan entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = null;
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERNAME;
		
		private string _TEN_NHANVIEN;
		
		private string _SDT;
		
		private string _EMAIL;
		
		private string _LOAI_NV;
		
		private EntitySet<LichTrinh> _LichTrinhs;
		
		private EntitySet<LichTrinh> _LichTrinhs1;
		
		private EntityRef<userAccount> _userAccount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnTEN_NHANVIENChanging(string value);
    partial void OnTEN_NHANVIENChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnLOAI_NVChanging(string value);
    partial void OnLOAI_NVChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._LichTrinhs = new EntitySet<LichTrinh>(new Action<LichTrinh>(this.attach_LichTrinhs), new Action<LichTrinh>(this.detach_LichTrinhs));
			this._LichTrinhs1 = new EntitySet<LichTrinh>(new Action<LichTrinh>(this.attach_LichTrinhs1), new Action<LichTrinh>(this.detach_LichTrinhs1));
			this._userAccount = default(EntityRef<userAccount>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					if (this._userAccount.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_NHANVIEN", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TEN_NHANVIEN
		{
			get
			{
				return this._TEN_NHANVIEN;
			}
			set
			{
				if ((this._TEN_NHANVIEN != value))
				{
					this.OnTEN_NHANVIENChanging(value);
					this.SendPropertyChanging();
					this._TEN_NHANVIEN = value;
					this.SendPropertyChanged("TEN_NHANVIEN");
					this.OnTEN_NHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAI_NV", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string LOAI_NV
		{
			get
			{
				return this._LOAI_NV;
			}
			set
			{
				if ((this._LOAI_NV != value))
				{
					this.OnLOAI_NVChanging(value);
					this.SendPropertyChanging();
					this._LOAI_NV = value;
					this.SendPropertyChanged("LOAI_NV");
					this.OnLOAI_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_LichTrinh", Storage="_LichTrinhs", ThisKey="USERNAME", OtherKey="NGUOI_TAO_LICH_TRINH")]
		public EntitySet<LichTrinh> LichTrinhs
		{
			get
			{
				return this._LichTrinhs;
			}
			set
			{
				this._LichTrinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_LichTrinh1", Storage="_LichTrinhs1", ThisKey="USERNAME", OtherKey="TAIXE")]
		public EntitySet<LichTrinh> LichTrinhs1
		{
			get
			{
				return this._LichTrinhs1;
			}
			set
			{
				this._LichTrinhs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="userAccount_NHANVIEN", Storage="_userAccount", ThisKey="USERNAME", OtherKey="username", IsForeignKey=true)]
		public userAccount userAccount
		{
			get
			{
				return this._userAccount.Entity;
			}
			set
			{
				userAccount previousValue = this._userAccount.Entity;
				if (((previousValue != value) 
							|| (this._userAccount.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._userAccount.Entity = null;
						previousValue.NHANVIEN = null;
					}
					this._userAccount.Entity = value;
					if ((value != null))
					{
						value.NHANVIEN = this;
						this._USERNAME = value.username;
					}
					else
					{
						this._USERNAME = default(string);
					}
					this.SendPropertyChanged("userAccount");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichTrinhs(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_LichTrinhs(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_LichTrinhs1(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN1 = this;
		}
		
		private void detach_LichTrinhs1(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHUONG_THUC_THANH_TOAN")]
	public partial class PHUONG_THUC_THANH_TOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_PTTT;
		
		private string _TEN_PHUONG_THUC_THANH_TOAN;
		
		private string _CACH_THUC_THANH_TOAN;
		
		private EntitySet<Ve> _Ves;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PTTTChanging(string value);
    partial void OnID_PTTTChanged();
    partial void OnTEN_PHUONG_THUC_THANH_TOANChanging(string value);
    partial void OnTEN_PHUONG_THUC_THANH_TOANChanged();
    partial void OnCACH_THUC_THANH_TOANChanging(string value);
    partial void OnCACH_THUC_THANH_TOANChanged();
    #endregion
		
		public PHUONG_THUC_THANH_TOAN()
		{
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PTTT", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_PTTT
		{
			get
			{
				return this._ID_PTTT;
			}
			set
			{
				if ((this._ID_PTTT != value))
				{
					this.OnID_PTTTChanging(value);
					this.SendPropertyChanging();
					this._ID_PTTT = value;
					this.SendPropertyChanged("ID_PTTT");
					this.OnID_PTTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_PHUONG_THUC_THANH_TOAN", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TEN_PHUONG_THUC_THANH_TOAN
		{
			get
			{
				return this._TEN_PHUONG_THUC_THANH_TOAN;
			}
			set
			{
				if ((this._TEN_PHUONG_THUC_THANH_TOAN != value))
				{
					this.OnTEN_PHUONG_THUC_THANH_TOANChanging(value);
					this.SendPropertyChanging();
					this._TEN_PHUONG_THUC_THANH_TOAN = value;
					this.SendPropertyChanged("TEN_PHUONG_THUC_THANH_TOAN");
					this.OnTEN_PHUONG_THUC_THANH_TOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CACH_THUC_THANH_TOAN", DbType="VarChar(MAX)")]
		public string CACH_THUC_THANH_TOAN
		{
			get
			{
				return this._CACH_THUC_THANH_TOAN;
			}
			set
			{
				if ((this._CACH_THUC_THANH_TOAN != value))
				{
					this.OnCACH_THUC_THANH_TOANChanging(value);
					this.SendPropertyChanging();
					this._CACH_THUC_THANH_TOAN = value;
					this.SendPropertyChanged("CACH_THUC_THANH_TOAN");
					this.OnCACH_THUC_THANH_TOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUONG_THUC_THANH_TOAN_Ve", Storage="_Ves", ThisKey="ID_PTTT", OtherKey="PHUONG_THUC_THANH_TOAN")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.PHUONG_THUC_THANH_TOAN1 = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.PHUONG_THUC_THANH_TOAN1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuyenDuong")]
	public partial class TuyenDuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TUYEN;
		
		private string _TEN_TUYEN;
		
		private int _DIEM_DAU;
		
		private int _DIEM_CUOI;
		
		private double _KHOANG_CACH;
		
		private double _THOI_GIAN_DUY_CHUYEN;
		
		private string _TINH_TRANG;
		
		private EntitySet<LichTrinh> _LichTrinhs;
		
		private EntityRef<DiaDiem> _DiaDiem;
		
		private EntityRef<DiaDiem> _DiaDiem1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TUYENChanging(int value);
    partial void OnID_TUYENChanged();
    partial void OnTEN_TUYENChanging(string value);
    partial void OnTEN_TUYENChanged();
    partial void OnDIEM_DAUChanging(int value);
    partial void OnDIEM_DAUChanged();
    partial void OnDIEM_CUOIChanging(int value);
    partial void OnDIEM_CUOIChanged();
    partial void OnKHOANG_CACHChanging(double value);
    partial void OnKHOANG_CACHChanged();
    partial void OnTHOI_GIAN_DUY_CHUYENChanging(double value);
    partial void OnTHOI_GIAN_DUY_CHUYENChanged();
    partial void OnTINH_TRANGChanging(string value);
    partial void OnTINH_TRANGChanged();
    #endregion
		
		public TuyenDuong()
		{
			this._LichTrinhs = new EntitySet<LichTrinh>(new Action<LichTrinh>(this.attach_LichTrinhs), new Action<LichTrinh>(this.detach_LichTrinhs));
			this._DiaDiem = default(EntityRef<DiaDiem>);
			this._DiaDiem1 = default(EntityRef<DiaDiem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TUYEN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TUYEN
		{
			get
			{
				return this._ID_TUYEN;
			}
			set
			{
				if ((this._ID_TUYEN != value))
				{
					this.OnID_TUYENChanging(value);
					this.SendPropertyChanging();
					this._ID_TUYEN = value;
					this.SendPropertyChanged("ID_TUYEN");
					this.OnID_TUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TUYEN", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TEN_TUYEN
		{
			get
			{
				return this._TEN_TUYEN;
			}
			set
			{
				if ((this._TEN_TUYEN != value))
				{
					this.OnTEN_TUYENChanging(value);
					this.SendPropertyChanging();
					this._TEN_TUYEN = value;
					this.SendPropertyChanged("TEN_TUYEN");
					this.OnTEN_TUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEM_DAU", DbType="Int NOT NULL")]
		public int DIEM_DAU
		{
			get
			{
				return this._DIEM_DAU;
			}
			set
			{
				if ((this._DIEM_DAU != value))
				{
					if (this._DiaDiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDIEM_DAUChanging(value);
					this.SendPropertyChanging();
					this._DIEM_DAU = value;
					this.SendPropertyChanged("DIEM_DAU");
					this.OnDIEM_DAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEM_CUOI", DbType="Int NOT NULL")]
		public int DIEM_CUOI
		{
			get
			{
				return this._DIEM_CUOI;
			}
			set
			{
				if ((this._DIEM_CUOI != value))
				{
					if (this._DiaDiem1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDIEM_CUOIChanging(value);
					this.SendPropertyChanging();
					this._DIEM_CUOI = value;
					this.SendPropertyChanged("DIEM_CUOI");
					this.OnDIEM_CUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHOANG_CACH", DbType="Float NOT NULL")]
		public double KHOANG_CACH
		{
			get
			{
				return this._KHOANG_CACH;
			}
			set
			{
				if ((this._KHOANG_CACH != value))
				{
					this.OnKHOANG_CACHChanging(value);
					this.SendPropertyChanging();
					this._KHOANG_CACH = value;
					this.SendPropertyChanged("KHOANG_CACH");
					this.OnKHOANG_CACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOI_GIAN_DUY_CHUYEN", DbType="Float NOT NULL")]
		public double THOI_GIAN_DUY_CHUYEN
		{
			get
			{
				return this._THOI_GIAN_DUY_CHUYEN;
			}
			set
			{
				if ((this._THOI_GIAN_DUY_CHUYEN != value))
				{
					this.OnTHOI_GIAN_DUY_CHUYENChanging(value);
					this.SendPropertyChanging();
					this._THOI_GIAN_DUY_CHUYEN = value;
					this.SendPropertyChanged("THOI_GIAN_DUY_CHUYEN");
					this.OnTHOI_GIAN_DUY_CHUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINH_TRANG", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string TINH_TRANG
		{
			get
			{
				return this._TINH_TRANG;
			}
			set
			{
				if ((this._TINH_TRANG != value))
				{
					this.OnTINH_TRANGChanging(value);
					this.SendPropertyChanging();
					this._TINH_TRANG = value;
					this.SendPropertyChanged("TINH_TRANG");
					this.OnTINH_TRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenDuong_LichTrinh", Storage="_LichTrinhs", ThisKey="ID_TUYEN", OtherKey="ID_TUYEN_DUONG")]
		public EntitySet<LichTrinh> LichTrinhs
		{
			get
			{
				return this._LichTrinhs;
			}
			set
			{
				this._LichTrinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TuyenDuong", Storage="_DiaDiem", ThisKey="DIEM_DAU", OtherKey="ID_DIADIEM", IsForeignKey=true)]
		public DiaDiem DiaDiem
		{
			get
			{
				return this._DiaDiem.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem.Entity = null;
						previousValue.TuyenDuongs.Remove(this);
					}
					this._DiaDiem.Entity = value;
					if ((value != null))
					{
						value.TuyenDuongs.Add(this);
						this._DIEM_DAU = value.ID_DIADIEM;
					}
					else
					{
						this._DIEM_DAU = default(int);
					}
					this.SendPropertyChanged("DiaDiem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TuyenDuong1", Storage="_DiaDiem1", ThisKey="DIEM_CUOI", OtherKey="ID_DIADIEM", IsForeignKey=true)]
		public DiaDiem DiaDiem1
		{
			get
			{
				return this._DiaDiem1.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem1.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem1.Entity = null;
						previousValue.TuyenDuongs1.Remove(this);
					}
					this._DiaDiem1.Entity = value;
					if ((value != null))
					{
						value.TuyenDuongs1.Add(this);
						this._DIEM_CUOI = value.ID_DIADIEM;
					}
					else
					{
						this._DIEM_CUOI = default(int);
					}
					this.SendPropertyChanged("DiaDiem1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichTrinhs(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.TuyenDuong = this;
		}
		
		private void detach_LichTrinhs(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.TuyenDuong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThemTramDungChan")]
	public partial class ThemTramDungChan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_TRAMDUNGCHAN;
		
		private string _MA_LICH_TRINH;
		
		private System.Nullable<System.DateTime> _THOIGIANDEN;
		
		private EntityRef<LichTrinh> _LichTrinh;
		
		private EntityRef<TramDungChan> _TramDungChan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TRAMDUNGCHANChanging(string value);
    partial void OnID_TRAMDUNGCHANChanged();
    partial void OnMA_LICH_TRINHChanging(string value);
    partial void OnMA_LICH_TRINHChanged();
    partial void OnTHOIGIANDENChanging(System.Nullable<System.DateTime> value);
    partial void OnTHOIGIANDENChanged();
    #endregion
		
		public ThemTramDungChan()
		{
			this._LichTrinh = default(EntityRef<LichTrinh>);
			this._TramDungChan = default(EntityRef<TramDungChan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TRAMDUNGCHAN", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_TRAMDUNGCHAN
		{
			get
			{
				return this._ID_TRAMDUNGCHAN;
			}
			set
			{
				if ((this._ID_TRAMDUNGCHAN != value))
				{
					if (this._TramDungChan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TRAMDUNGCHANChanging(value);
					this.SendPropertyChanging();
					this._ID_TRAMDUNGCHAN = value;
					this.SendPropertyChanged("ID_TRAMDUNGCHAN");
					this.OnID_TRAMDUNGCHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LICH_TRINH", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_LICH_TRINH
		{
			get
			{
				return this._MA_LICH_TRINH;
			}
			set
			{
				if ((this._MA_LICH_TRINH != value))
				{
					if (this._LichTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._MA_LICH_TRINH = value;
					this.SendPropertyChanged("MA_LICH_TRINH");
					this.OnMA_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANDEN", DbType="DateTime")]
		public System.Nullable<System.DateTime> THOIGIANDEN
		{
			get
			{
				return this._THOIGIANDEN;
			}
			set
			{
				if ((this._THOIGIANDEN != value))
				{
					this.OnTHOIGIANDENChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANDEN = value;
					this.SendPropertyChanged("THOIGIANDEN");
					this.OnTHOIGIANDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_ThemTramDungChan", Storage="_LichTrinh", ThisKey="MA_LICH_TRINH", OtherKey="MA_LICH_TRINH", IsForeignKey=true)]
		public LichTrinh LichTrinh
		{
			get
			{
				return this._LichTrinh.Entity;
			}
			set
			{
				LichTrinh previousValue = this._LichTrinh.Entity;
				if (((previousValue != value) 
							|| (this._LichTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichTrinh.Entity = null;
						previousValue.ThemTramDungChans.Remove(this);
					}
					this._LichTrinh.Entity = value;
					if ((value != null))
					{
						value.ThemTramDungChans.Add(this);
						this._MA_LICH_TRINH = value.MA_LICH_TRINH;
					}
					else
					{
						this._MA_LICH_TRINH = default(string);
					}
					this.SendPropertyChanged("LichTrinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TramDungChan_ThemTramDungChan", Storage="_TramDungChan", ThisKey="ID_TRAMDUNGCHAN", OtherKey="ID_TRAMDUNGCHAN", IsForeignKey=true)]
		public TramDungChan TramDungChan
		{
			get
			{
				return this._TramDungChan.Entity;
			}
			set
			{
				TramDungChan previousValue = this._TramDungChan.Entity;
				if (((previousValue != value) 
							|| (this._TramDungChan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TramDungChan.Entity = null;
						previousValue.ThemTramDungChans.Remove(this);
					}
					this._TramDungChan.Entity = value;
					if ((value != null))
					{
						value.ThemTramDungChans.Add(this);
						this._ID_TRAMDUNGCHAN = value.ID_TRAMDUNGCHAN;
					}
					else
					{
						this._ID_TRAMDUNGCHAN = default(string);
					}
					this.SendPropertyChanged("TramDungChan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TramDungChan")]
	public partial class TramDungChan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_TRAMDUNGCHAN;
		
		private string _TEN_TRAMDUNGCHAN;
		
		private int _ID_DIADIEM;
		
		private string _DIA_CHI;
		
		private EntitySet<ThemTramDungChan> _ThemTramDungChans;
		
		private EntitySet<Ve> _Ves;
		
		private EntitySet<Ve> _Ves1;
		
		private EntityRef<DiaDiem> _DiaDiem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TRAMDUNGCHANChanging(string value);
    partial void OnID_TRAMDUNGCHANChanged();
    partial void OnTEN_TRAMDUNGCHANChanging(string value);
    partial void OnTEN_TRAMDUNGCHANChanged();
    partial void OnID_DIADIEMChanging(int value);
    partial void OnID_DIADIEMChanged();
    partial void OnDIA_CHIChanging(string value);
    partial void OnDIA_CHIChanged();
    #endregion
		
		public TramDungChan()
		{
			this._ThemTramDungChans = new EntitySet<ThemTramDungChan>(new Action<ThemTramDungChan>(this.attach_ThemTramDungChans), new Action<ThemTramDungChan>(this.detach_ThemTramDungChans));
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			this._Ves1 = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves1), new Action<Ve>(this.detach_Ves1));
			this._DiaDiem = default(EntityRef<DiaDiem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TRAMDUNGCHAN", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_TRAMDUNGCHAN
		{
			get
			{
				return this._ID_TRAMDUNGCHAN;
			}
			set
			{
				if ((this._ID_TRAMDUNGCHAN != value))
				{
					this.OnID_TRAMDUNGCHANChanging(value);
					this.SendPropertyChanging();
					this._ID_TRAMDUNGCHAN = value;
					this.SendPropertyChanged("ID_TRAMDUNGCHAN");
					this.OnID_TRAMDUNGCHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TRAMDUNGCHAN", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TEN_TRAMDUNGCHAN
		{
			get
			{
				return this._TEN_TRAMDUNGCHAN;
			}
			set
			{
				if ((this._TEN_TRAMDUNGCHAN != value))
				{
					this.OnTEN_TRAMDUNGCHANChanging(value);
					this.SendPropertyChanging();
					this._TEN_TRAMDUNGCHAN = value;
					this.SendPropertyChanged("TEN_TRAMDUNGCHAN");
					this.OnTEN_TRAMDUNGCHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DIADIEM", DbType="Int NOT NULL")]
		public int ID_DIADIEM
		{
			get
			{
				return this._ID_DIADIEM;
			}
			set
			{
				if ((this._ID_DIADIEM != value))
				{
					if (this._DiaDiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DIADIEMChanging(value);
					this.SendPropertyChanging();
					this._ID_DIADIEM = value;
					this.SendPropertyChanged("ID_DIADIEM");
					this.OnID_DIADIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_CHI", DbType="NVarChar(258) NOT NULL", CanBeNull=false)]
		public string DIA_CHI
		{
			get
			{
				return this._DIA_CHI;
			}
			set
			{
				if ((this._DIA_CHI != value))
				{
					this.OnDIA_CHIChanging(value);
					this.SendPropertyChanging();
					this._DIA_CHI = value;
					this.SendPropertyChanged("DIA_CHI");
					this.OnDIA_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TramDungChan_ThemTramDungChan", Storage="_ThemTramDungChans", ThisKey="ID_TRAMDUNGCHAN", OtherKey="ID_TRAMDUNGCHAN")]
		public EntitySet<ThemTramDungChan> ThemTramDungChans
		{
			get
			{
				return this._ThemTramDungChans;
			}
			set
			{
				this._ThemTramDungChans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TramDungChan_Ve", Storage="_Ves", ThisKey="ID_TRAMDUNGCHAN", OtherKey="DIEM_DOAN")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TramDungChan_Ve1", Storage="_Ves1", ThisKey="ID_TRAMDUNGCHAN", OtherKey="DIEM_TRA")]
		public EntitySet<Ve> Ves1
		{
			get
			{
				return this._Ves1;
			}
			set
			{
				this._Ves1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TramDungChan", Storage="_DiaDiem", ThisKey="ID_DIADIEM", OtherKey="ID_DIADIEM", IsForeignKey=true)]
		public DiaDiem DiaDiem
		{
			get
			{
				return this._DiaDiem.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem.Entity = null;
						previousValue.TramDungChans.Remove(this);
					}
					this._DiaDiem.Entity = value;
					if ((value != null))
					{
						value.TramDungChans.Add(this);
						this._ID_DIADIEM = value.ID_DIADIEM;
					}
					else
					{
						this._ID_DIADIEM = default(int);
					}
					this.SendPropertyChanged("DiaDiem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThemTramDungChans(ThemTramDungChan entity)
		{
			this.SendPropertyChanging();
			entity.TramDungChan = this;
		}
		
		private void detach_ThemTramDungChans(ThemTramDungChan entity)
		{
			this.SendPropertyChanging();
			entity.TramDungChan = null;
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.TramDungChan = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.TramDungChan = null;
		}
		
		private void attach_Ves1(Ve entity)
		{
			this.SendPropertyChanging();
			entity.TramDungChan1 = this;
		}
		
		private void detach_Ves1(Ve entity)
		{
			this.SendPropertyChanging();
			entity.TramDungChan1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userAccount")]
	public partial class userAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
		private string _role;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    #endregion
		
		public userAccount()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="userAccount_KhachHang", Storage="_KhachHang", ThisKey="username", OtherKey="USERNAME", IsUnique=true, IsForeignKey=false)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.userAccount = null;
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.userAccount = this;
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="userAccount_NHANVIEN", Storage="_NHANVIEN", ThisKey="username", OtherKey="USERNAME", IsUnique=true, IsForeignKey=false)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.userAccount = null;
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.userAccount = this;
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ve")]
	public partial class Ve : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_VE;
		
		private string _ID_KHACH_HANG;
		
		private string _ID_LICH_TRINH;
		
		private System.DateTime _NGAY_DAT_VE;
		
		private double _TONG_TIEN;
		
		private string _DIEM_DOAN;
		
		private string _DIEM_TRA;
		
		private string _QR_CODE;
		
		private string _TRANG_THAI;
		
		private string _PHUONG_THUC_THANH_TOAN;
		
		private EntitySet<ChiTietVe> _ChiTietVes;
		
		private EntityRef<TramDungChan> _TramDungChan;
		
		private EntityRef<TramDungChan> _TramDungChan1;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<LichTrinh> _LichTrinh;
		
		private EntityRef<PHUONG_THUC_THANH_TOAN> _PHUONG_THUC_THANH_TOAN1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VEChanging(string value);
    partial void OnID_VEChanged();
    partial void OnID_KHACH_HANGChanging(string value);
    partial void OnID_KHACH_HANGChanged();
    partial void OnID_LICH_TRINHChanging(string value);
    partial void OnID_LICH_TRINHChanged();
    partial void OnNGAY_DAT_VEChanging(System.DateTime value);
    partial void OnNGAY_DAT_VEChanged();
    partial void OnTONG_TIENChanging(double value);
    partial void OnTONG_TIENChanged();
    partial void OnDIEM_DOANChanging(string value);
    partial void OnDIEM_DOANChanged();
    partial void OnDIEM_TRAChanging(string value);
    partial void OnDIEM_TRAChanged();
    partial void OnQR_CODEChanging(string value);
    partial void OnQR_CODEChanged();
    partial void OnTRANG_THAIChanging(string value);
    partial void OnTRANG_THAIChanged();
    partial void OnPHUONG_THUC_THANH_TOANChanging(string value);
    partial void OnPHUONG_THUC_THANH_TOANChanged();
    #endregion
		
		public Ve()
		{
			this._ChiTietVes = new EntitySet<ChiTietVe>(new Action<ChiTietVe>(this.attach_ChiTietVes), new Action<ChiTietVe>(this.detach_ChiTietVes));
			this._TramDungChan = default(EntityRef<TramDungChan>);
			this._TramDungChan1 = default(EntityRef<TramDungChan>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._LichTrinh = default(EntityRef<LichTrinh>);
			this._PHUONG_THUC_THANH_TOAN1 = default(EntityRef<PHUONG_THUC_THANH_TOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VE", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_VE
		{
			get
			{
				return this._ID_VE;
			}
			set
			{
				if ((this._ID_VE != value))
				{
					this.OnID_VEChanging(value);
					this.SendPropertyChanging();
					this._ID_VE = value;
					this.SendPropertyChanged("ID_VE");
					this.OnID_VEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KHACH_HANG", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string ID_KHACH_HANG
		{
			get
			{
				return this._ID_KHACH_HANG;
			}
			set
			{
				if ((this._ID_KHACH_HANG != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KHACH_HANGChanging(value);
					this.SendPropertyChanging();
					this._ID_KHACH_HANG = value;
					this.SendPropertyChanged("ID_KHACH_HANG");
					this.OnID_KHACH_HANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LICH_TRINH", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string ID_LICH_TRINH
		{
			get
			{
				return this._ID_LICH_TRINH;
			}
			set
			{
				if ((this._ID_LICH_TRINH != value))
				{
					if (this._LichTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._ID_LICH_TRINH = value;
					this.SendPropertyChanged("ID_LICH_TRINH");
					this.OnID_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_DAT_VE", DbType="DateTime NOT NULL")]
		public System.DateTime NGAY_DAT_VE
		{
			get
			{
				return this._NGAY_DAT_VE;
			}
			set
			{
				if ((this._NGAY_DAT_VE != value))
				{
					this.OnNGAY_DAT_VEChanging(value);
					this.SendPropertyChanging();
					this._NGAY_DAT_VE = value;
					this.SendPropertyChanged("NGAY_DAT_VE");
					this.OnNGAY_DAT_VEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONG_TIEN", DbType="Float NOT NULL")]
		public double TONG_TIEN
		{
			get
			{
				return this._TONG_TIEN;
			}
			set
			{
				if ((this._TONG_TIEN != value))
				{
					this.OnTONG_TIENChanging(value);
					this.SendPropertyChanging();
					this._TONG_TIEN = value;
					this.SendPropertyChanged("TONG_TIEN");
					this.OnTONG_TIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEM_DOAN", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string DIEM_DOAN
		{
			get
			{
				return this._DIEM_DOAN;
			}
			set
			{
				if ((this._DIEM_DOAN != value))
				{
					if (this._TramDungChan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDIEM_DOANChanging(value);
					this.SendPropertyChanging();
					this._DIEM_DOAN = value;
					this.SendPropertyChanged("DIEM_DOAN");
					this.OnDIEM_DOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEM_TRA", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string DIEM_TRA
		{
			get
			{
				return this._DIEM_TRA;
			}
			set
			{
				if ((this._DIEM_TRA != value))
				{
					if (this._TramDungChan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDIEM_TRAChanging(value);
					this.SendPropertyChanging();
					this._DIEM_TRA = value;
					this.SendPropertyChanged("DIEM_TRA");
					this.OnDIEM_TRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QR_CODE", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string QR_CODE
		{
			get
			{
				return this._QR_CODE;
			}
			set
			{
				if ((this._QR_CODE != value))
				{
					this.OnQR_CODEChanging(value);
					this.SendPropertyChanging();
					this._QR_CODE = value;
					this.SendPropertyChanged("QR_CODE");
					this.OnQR_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANG_THAI", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string TRANG_THAI
		{
			get
			{
				return this._TRANG_THAI;
			}
			set
			{
				if ((this._TRANG_THAI != value))
				{
					this.OnTRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._TRANG_THAI = value;
					this.SendPropertyChanged("TRANG_THAI");
					this.OnTRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHUONG_THUC_THANH_TOAN", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string PHUONG_THUC_THANH_TOAN
		{
			get
			{
				return this._PHUONG_THUC_THANH_TOAN;
			}
			set
			{
				if ((this._PHUONG_THUC_THANH_TOAN != value))
				{
					if (this._PHUONG_THUC_THANH_TOAN1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPHUONG_THUC_THANH_TOANChanging(value);
					this.SendPropertyChanging();
					this._PHUONG_THUC_THANH_TOAN = value;
					this.SendPropertyChanged("PHUONG_THUC_THANH_TOAN");
					this.OnPHUONG_THUC_THANH_TOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ve_ChiTietVe", Storage="_ChiTietVes", ThisKey="ID_VE", OtherKey="ID_VE")]
		public EntitySet<ChiTietVe> ChiTietVes
		{
			get
			{
				return this._ChiTietVes;
			}
			set
			{
				this._ChiTietVes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TramDungChan_Ve", Storage="_TramDungChan", ThisKey="DIEM_DOAN", OtherKey="ID_TRAMDUNGCHAN", IsForeignKey=true)]
		public TramDungChan TramDungChan
		{
			get
			{
				return this._TramDungChan.Entity;
			}
			set
			{
				TramDungChan previousValue = this._TramDungChan.Entity;
				if (((previousValue != value) 
							|| (this._TramDungChan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TramDungChan.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._TramDungChan.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._DIEM_DOAN = value.ID_TRAMDUNGCHAN;
					}
					else
					{
						this._DIEM_DOAN = default(string);
					}
					this.SendPropertyChanged("TramDungChan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TramDungChan_Ve1", Storage="_TramDungChan1", ThisKey="DIEM_TRA", OtherKey="ID_TRAMDUNGCHAN", IsForeignKey=true)]
		public TramDungChan TramDungChan1
		{
			get
			{
				return this._TramDungChan1.Entity;
			}
			set
			{
				TramDungChan previousValue = this._TramDungChan1.Entity;
				if (((previousValue != value) 
							|| (this._TramDungChan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TramDungChan1.Entity = null;
						previousValue.Ves1.Remove(this);
					}
					this._TramDungChan1.Entity = value;
					if ((value != null))
					{
						value.Ves1.Add(this);
						this._DIEM_TRA = value.ID_TRAMDUNGCHAN;
					}
					else
					{
						this._DIEM_TRA = default(string);
					}
					this.SendPropertyChanged("TramDungChan1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_Ve", Storage="_KhachHang", ThisKey="ID_KHACH_HANG", OtherKey="USERNAME", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._ID_KHACH_HANG = value.USERNAME;
					}
					else
					{
						this._ID_KHACH_HANG = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_Ve", Storage="_LichTrinh", ThisKey="ID_LICH_TRINH", OtherKey="MA_LICH_TRINH", IsForeignKey=true)]
		public LichTrinh LichTrinh
		{
			get
			{
				return this._LichTrinh.Entity;
			}
			set
			{
				LichTrinh previousValue = this._LichTrinh.Entity;
				if (((previousValue != value) 
							|| (this._LichTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichTrinh.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._LichTrinh.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._ID_LICH_TRINH = value.MA_LICH_TRINH;
					}
					else
					{
						this._ID_LICH_TRINH = default(string);
					}
					this.SendPropertyChanged("LichTrinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUONG_THUC_THANH_TOAN_Ve", Storage="_PHUONG_THUC_THANH_TOAN1", ThisKey="PHUONG_THUC_THANH_TOAN", OtherKey="ID_PTTT", IsForeignKey=true)]
		public PHUONG_THUC_THANH_TOAN PHUONG_THUC_THANH_TOAN1
		{
			get
			{
				return this._PHUONG_THUC_THANH_TOAN1.Entity;
			}
			set
			{
				PHUONG_THUC_THANH_TOAN previousValue = this._PHUONG_THUC_THANH_TOAN1.Entity;
				if (((previousValue != value) 
							|| (this._PHUONG_THUC_THANH_TOAN1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHUONG_THUC_THANH_TOAN1.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._PHUONG_THUC_THANH_TOAN1.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._PHUONG_THUC_THANH_TOAN = value.ID_PTTT;
					}
					else
					{
						this._PHUONG_THUC_THANH_TOAN = default(string);
					}
					this.SendPropertyChanged("PHUONG_THUC_THANH_TOAN1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietVes(ChiTietVe entity)
		{
			this.SendPropertyChanging();
			entity.Ve = this;
		}
		
		private void detach_ChiTietVes(ChiTietVe entity)
		{
			this.SendPropertyChanging();
			entity.Ve = null;
		}
	}
}
#pragma warning restore 1591
