<?xml version="1.0" encoding="utf-8"?><Database Name="NHAXE_QUOCVUONG" Class="NhaXeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-I22SAC7\TKHANGDI;Initial Catalog=NHAXE_QUOCVUONG;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NHAXE_QUOCVUONGConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietVe" Member="ChiTietVes">
    <Type Name="ChiTietVe">
      <Column Name="ID_VE" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VI_TRI_NGOI" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QR_CODE" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TRANG_THAI" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="Ghe_ChiTietVe" Member="Ghe" ThisKey="VI_TRI_NGOI" OtherKey="ID_GHE" Type="Ghe" IsForeignKey="true" />
      <Association Name="Ve_ChiTietVe" Member="Ve" ThisKey="ID_VE" OtherKey="ID_VE" Type="Ve" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Xe" Member="Xes">
    <Type Name="Xe">
      <Column Name="ID_XE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BIEN_SO_XE" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="LOAI_XE" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="SO_GHE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_THEM_XE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Xe_LichTrinh" Member="LichTrinhs" ThisKey="ID_XE" OtherKey="ID_XE" Type="LichTrinh" />
    </Type>
  </Table>
  <Table Name="dbo.DiaDiem" Member="DiaDiems">
    <Type Name="DiaDiem">
      <Column Name="ID_DIADIEM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_TINH_THANH" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="DiaDiem_TramDungChan" Member="TramDungChans" ThisKey="ID_DIADIEM" OtherKey="ID_DIADIEM" Type="TramDungChan" />
      <Association Name="DiaDiem_TuyenDuong" Member="TuyenDuongs" ThisKey="ID_DIADIEM" OtherKey="DIEM_DAU" Type="TuyenDuong" />
      <Association Name="DiaDiem_TuyenDuong1" Member="TuyenDuongs1" ThisKey="ID_DIADIEM" OtherKey="DIEM_CUOI" Type="TuyenDuong" />
    </Type>
  </Table>
  <Table Name="dbo.DoanhThu" Member="DoanhThus">
    <Type Name="DoanhThu">
      <Column Name="ID_DOANHTHU" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_LICH_TRINH" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="SO_VE_DA_DAT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="LichTrinh_DoanhThu" Member="LichTrinh" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="LichTrinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ghe" Member="Ghes">
    <Type Name="Ghe">
      <Column Name="ID_GHE" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VI_TRI_NGOI" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MA_LICH_TRINH" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TINH_TRANG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Ghe_ChiTietVe" Member="ChiTietVes" ThisKey="ID_GHE" OtherKey="VI_TRI_NGOI" Type="ChiTietVe" />
      <Association Name="LichTrinh_Ghe" Member="LichTrinh" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="LichTrinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_KHACH_HANG" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="SO_DIEN_THOAI" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_Ve" Member="Ves" ThisKey="USERNAME" OtherKey="ID_KHACH_HANG" Type="Ve" />
      <Association Name="userAccount_KhachHang" Member="userAccount" ThisKey="USERNAME" OtherKey="username" Type="userAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichTrinh" Member="LichTrinhs">
    <Type Name="LichTrinh">
      <Column Name="MA_LICH_TRINH" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_TUYEN_DUONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KHOI_HANH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KET_THUC" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GIA_VE" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ID_XE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CHI_PHI_PHAT_SINH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TAIXE" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_TAO_LICH_TRINH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NGUOI_TAO_LICH_TRINH" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="LichTrinh_DoanhThu" Member="DoanhThus" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="DoanhThu" />
      <Association Name="LichTrinh_Ghe" Member="Ghes" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="Ghe" />
      <Association Name="LichTrinh_ThemTramDungChan" Member="ThemTramDungChans" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="ThemTramDungChan" />
      <Association Name="LichTrinh_Ve" Member="Ves" ThisKey="MA_LICH_TRINH" OtherKey="ID_LICH_TRINH" Type="Ve" />
      <Association Name="Xe_LichTrinh" Member="Xe" ThisKey="ID_XE" OtherKey="ID_XE" Type="Xe" IsForeignKey="true" />
      <Association Name="NHANVIEN_LichTrinh" Member="NHANVIEN" ThisKey="NGUOI_TAO_LICH_TRINH" OtherKey="USERNAME" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="NHANVIEN_LichTrinh1" Member="NHANVIEN1" ThisKey="TAIXE" OtherKey="USERNAME" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="TuyenDuong_LichTrinh" Member="TuyenDuong" ThisKey="ID_TUYEN_DUONG" OtherKey="ID_TUYEN" Type="TuyenDuong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_NHANVIEN" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="LOAI_NV" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Association Name="NHANVIEN_LichTrinh" Member="LichTrinhs" ThisKey="USERNAME" OtherKey="NGUOI_TAO_LICH_TRINH" Type="LichTrinh" />
      <Association Name="NHANVIEN_LichTrinh1" Member="LichTrinhs1" ThisKey="USERNAME" OtherKey="TAIXE" Type="LichTrinh" />
      <Association Name="userAccount_NHANVIEN" Member="userAccount" ThisKey="USERNAME" OtherKey="username" Type="userAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThemTramDungChan" Member="ThemTramDungChans">
    <Type Name="ThemTramDungChan">
      <Column Name="ID_TRAMDUNGCHAN" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_LICH_TRINH" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THOIGIANDEN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="LichTrinh_ThemTramDungChan" Member="LichTrinh" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="LichTrinh" IsForeignKey="true" />
      <Association Name="TramDungChan_ThemTramDungChan" Member="TramDungChan" ThisKey="ID_TRAMDUNGCHAN" OtherKey="ID_TRAMDUNGCHAN" Type="TramDungChan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TramDungChan" Member="TramDungChans">
    <Type Name="TramDungChan">
      <Column Name="ID_TRAMDUNGCHAN" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_TRAMDUNGCHAN" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ID_DIADIEM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DIA_CHI" Type="System.String" DbType="NVarChar(258) NOT NULL" CanBeNull="false" />
      <Association Name="TramDungChan_ThemTramDungChan" Member="ThemTramDungChans" ThisKey="ID_TRAMDUNGCHAN" OtherKey="ID_TRAMDUNGCHAN" Type="ThemTramDungChan" />
      <Association Name="DiaDiem_TramDungChan" Member="DiaDiem" ThisKey="ID_DIADIEM" OtherKey="ID_DIADIEM" Type="DiaDiem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TuyenDuong" Member="TuyenDuongs">
    <Type Name="TuyenDuong">
      <Column Name="ID_TUYEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_TUYEN" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DIEM_DAU" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DIEM_CUOI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KHOANG_CACH" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="THOI_GIAN_DUY_CHUYEN" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TINH_TRANG" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="TuyenDuong_LichTrinh" Member="LichTrinhs" ThisKey="ID_TUYEN" OtherKey="ID_TUYEN_DUONG" Type="LichTrinh" />
      <Association Name="DiaDiem_TuyenDuong" Member="DiaDiem" ThisKey="DIEM_DAU" OtherKey="ID_DIADIEM" Type="DiaDiem" IsForeignKey="true" />
      <Association Name="DiaDiem_TuyenDuong1" Member="DiaDiem1" ThisKey="DIEM_CUOI" OtherKey="ID_DIADIEM" Type="DiaDiem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.userAccount" Member="userAccounts">
    <Type Name="userAccount">
      <Column Name="username" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="userAccount_KhachHang" Member="KhachHang" ThisKey="username" OtherKey="USERNAME" Type="KhachHang" Cardinality="One" />
      <Association Name="userAccount_NHANVIEN" Member="NHANVIEN" ThisKey="username" OtherKey="USERNAME" Type="NHANVIEN" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Ve" Member="Ves">
    <Type Name="Ve">
      <Column Name="ID_VE" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_KHACH_HANG" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ID_LICH_TRINH" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_DAT_VE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TONG_TIEN" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Ve_ChiTietVe" Member="ChiTietVes" ThisKey="ID_VE" OtherKey="ID_VE" Type="ChiTietVe" />
      <Association Name="KhachHang_Ve" Member="KhachHang" ThisKey="ID_KHACH_HANG" OtherKey="USERNAME" Type="KhachHang" IsForeignKey="true" />
      <Association Name="LichTrinh_Ve" Member="LichTrinh" ThisKey="ID_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="LichTrinh" IsForeignKey="true" />
    </Type>
  </Table>
</Database>